name: imagemap-tools build
on : 
  push:
    branches:
      - master

jobs :
    build:
      name: react build
      runs-on: self-hosted        
      env:
        working-directory: ~/productions
      
      steps:
        - name: Checkout source code.
          uses: actions/checkout@master
          
        - name: install dependencies.
          run: yarn
          working-directory: ${{ env.working-directory}}

          
        - name: Build
          run: yarn build

