name: imagemap-tools build
on : 
  push:
    branches:
      - master

jobs :
    build:
      name: react build
      runs-on: self-hosted 
      
      steps:
        - name : checkout
          uses: actions/checkout@master
          with:
            fetch-depth: 1
