name: test imagemap-tools action
on : 
  push:
    branches:
      - master

jobs :
    build:
      name: react build
      runs-on: self-hosted 
      
      steps:
        - name : checkout
          uses: actions/checkout@master
          
        - name : test file create
          run : touch test.txt
