name: imagemap-tools build
on : 
  push:
    branches:
      - master

jobs :
    build:
      name: react build
      runs-on: self-hosted        
      env:
        working-directory: ~/productions
      
      steps:
          - uses: actions/checkout@master

        

