name: imagemap-tools build
on : 
  push:
    branches:
      - master

jobs :
    build:
      name: react build
      runs-on: self-hosted
      steps:
        - name: Checkout source code.
          uses: actions/checkout@master
          
        - name: install dependencies.
          run: yarn
          
        - name: Build
          run: yarn build
